
CREATE TABLE USER (

    ID BIGINT AUTO_INCREAMENT NOT NULL ,
    EMAIL VARCHAR(50) NOT NULL ,
    PASSWORD VARCHAR(100) NOT NULL ,
    NICKNAME VARCHAR(30) NOT NULL ,
    PHONE_NUMBER VARCHAR(200) NOT NULL ,
    CREATED_AT timestamp NOT NULL ,
    UPDATED_AT TIMESTAMP NOT NULL ,
    CONSTRAINT PK_USER_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_USER_NICKNAME UNIQUE (NICKNAME)
);